name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  release-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Release Build
      run: cargo build --release --verbose
    - name: Build Debian package
      run: cargo install cargo-deb && ./build_deb.sh
    - uses: actions/upload-artifact@v2
      with:
        name: gitnotes_linux_x86_64
        path: target/release/gitnotes
    - uses: actions/upload-artifact@v2
      with:
        name: gitnotes_linux_x86_64_debian
        path: target/debian/